project:
  type: website

# All icons on the menubar are from https://fontawesome.com/icons?d=gallery
website:
  reader-mode: true
  title: "SDS"
  navbar:
    left:
      - text: "Home"
        icon: fa-home
        href: index.qmd
      - text: "Awards"
        icon: fa-award
        menu:
          - text: Honors & Prizes
            href: awards.html
          - text: "Mu Sigma Rho"
            href: mu_sigma_rho.qmd
      - text: "Help"
        icon: fa-question-circle
        href: rmarkdown_problems.html
      - text: "Writing"
        icon: fa-pencil-alt
        menu:
          - text: "Publications"
            icon: fa-scroll
            href: https://scholarworks.smith.edu/sds/
          - text: "Newsletters"
            icon: fa-newspaper
          - text: "2024"
            href: sds_newsletter_2024.qmd
          - text: "2023"
            href: sds_newsletter_2023.qmd
          - text: "2022"
            href: sds_newsletter_2022.qmd
          - text: "2021"
            href: sds_newsletter_2021.html
          - text: "2020"
            href: sds_newsletter_2020.html
          - text: "2019"
            href: sds_newsletter_2019.html
          - text: "2018"
            href: sds_newsletter_2018.html
          - text: "2017"
            href: sds_newsletter_2017.html
          - text: "2016"
            href: sds_newsletter_2016.html
      - text: Teaching
        icon: fa-chalkboard-teacher
        menu:
          - text: "Ethics"
            icon: fa-book
            href: sds-www/ethics.Rmd
          - text: "Calendar"
            icon: fa-calendar-alt
            href: sds-www/JSE_calendar.Rmd
    right:
      - icon: fa-github
        href: https://github.com/SmithCollege-SDS
  page-footer: 
    left: "Website maintained by [Ben Baumer](http://www.science.smith.edu/~bbaumer)." 
    right: 
      - icon: github
        href: https://github.com/SmithCollege-SDS/smithcollege-sds.github.io/


format:
  html:
    theme: yeti
    highlight: pygments
    css: include/smith.css
    toc: true
    toc_float: true
