---
title: 'Honors & Prizes'
---

## Prizes

### Statistical & Data Sciences Research Prize

The program awards an annual prize to a student majoring in SDS who performed outstanding research during her time at Smith. 
The faculty meets every spring to review the research projects they have supervised and select the prize recipient, who is then notified at the annual Awards Ceremony the day before [Commencement](https://www.smith.edu/news-events/events/commencement).

#### Awardees

- 2024: Heng (Silvia) Song '24
- 2023: Quinn White '23
- 2022: Natalia Iannucci '22
- 2021: Audrey Bertin '21
- 2020: Jessica Keast '20
- 2019: Julianna Alvord '19
- 2018: Wencong (Priscilla) Li '18
- 2017: Weijia (Vega) Zhang '17

### Five College Statistics Prize

The [Five College Statistics](https://www.fivecolleges.edu/statistics/) prize is awarded to one student at each of the Five Colleges, at their discretion. The award may be presented to a student satisfying any one of the following criteria (based on faculty vote from that institution):

- outstanding independent research, thesis, or capstone course project in statistics
- outstanding service to statistics on their campus (or across campuses)
- outstanding use of Five College statistics resources
- outstanding non-senior pursuing further study in statistics

#### Awardees

- 2024: Christy Yang '25J and Vicky Xu '26 *(outstanding service to statistics)*
- 2023: Aushanae Haller '23J, Clara Li '23 *(outstanding service to statistics)*
- 2022: Sarah Gillespie '22J, Joyce Huang '22, Arris Moise '22, Chichi Wu '22 *(outstanding service to statistics)*
- 2021: Yujia (Starry) Zhou '21J and Hannah Snell '21 *(outstanding service to statistics)*
- 2020: Laneé Jung '20 and Fatima Keita '20 *(outstanding service to statistics)*
- 2019: Yue Kuang '19, Zixian Li '19, and Jingyi Liu '19 *(outstanding senior capstone project)*
- 2018: Paige Patrick 'AC and Rutendo Madziwo '19 *(outstanding service to statistics)*
- 2017: Abby Doctor '17 *(outstanding senior capstone project)*
- 2016: Yiwen Zhu '16 and Emma Beauchamp '16 *(outstanding theses)*
- 2015: Weijia (Vega) Zhang '18 *(outstanding non-senior)*

	
## Departmental Honors


```{r}
#| message: false
library(tidyverse)
honors <- tribble(
  ~year, ~student, ~designation, ~title, ~id, ~first_reader, ~second_reader,
  2024, "Heng (Silvia) Song '24", "High Honors (MST)", "Stochastic Processes and their Application in Bayesian Statistics", NA, "Kaitlyn Cook", "Jen Beichman (MTH)",
  2023, "Quinn White '23", "Highest Honors", "Using Sensitivity Analyses to Approximate Total COVID-19 Infections: State and County level in the United States, March 2021--March 2022", NA, "Ben Baumer", "Nick Reich (UMass)",
  2022, "Natalia Iannucci '22", "Highest Honors", "Improving Mutational Signature Detection in Cancer through Frequentist and Bayesian Hypothesis Testing", 2446, "Ben Baumer", "Giovanni Parmigiani (Harvard)",
  2021, "Audrey Bertin '21", "Highest Honors", "Addressing The Scientific Reproducibility Crisis Through Educational Software Integration", 2317, "Ben Baumer", "Albert Kim",
  2020, "Jessica Keast '20", "Highest Honors", "Twang Identification in American Folk and Country Music", 2227, "Katherine Kinnaird", "Albert Kim",
  2020, "Aoi Ogawa '20", "High Honors", "Estimating Microbial Diversity of Toxin Producing Bacteria from Soil Using Cellular Automata", 2251, "Katherine Halvorsen", "Chris Golé (MTH)", 
  2020, "Ziwei (Crystal) Zang '20", "High Honors", "Metabolites Prediction in Multiple Studies Using Machine Learning", 2290, "Katherine Halvorsen", "Ed Resnick (Memorial Sloan Kettering)",
  2019, "Julianna Alvord '19", "Highest Honors", "Modeling Racially Disproportionate Language on Twitter during NFL Gameplay", 2108, "Randi Garcia", "Ben Baumer",
  2018, "Wencong (Priscilla) Li '18", "Highest Honors", "Tools for understanding taxicab and e-hail service use in New York City", 2032, "Ben Baumer", "Jordan Crouser", 
  2017, "Weijia (Vega) Zhang '17", "High Honors", "Improving access to open-source data about the NYC bike sharing system (Citi Bike", 1871, "Ben Baumer", "Jordan Crouser",
)
honors |>
  mutate(
    link = paste0("[", title, "](https://scholarworks.smith.edu/theses/", id, ")" )
  ) |>
  select(year, student, designation, Title = link, first_reader, second_reader) |>
  janitor::clean_names(case = "title") |>
  knitr::kable()
```



	
## Competitions

### [ASA Five College DataFest](http://www.science.smith.edu/datafest/)

DataFest is a national undergraduate data analysis competition hosted at UMass each spring, in which students work in teams of up to five to extract insights from a complex, challenging data set over a weekend. 

Recent winners from Smith include:

- [2023](https://www.science.smith.edu/datafest/2023/04/10/recap-from-the-2023-asa-five-college-datafest/)
    - Best in Show: The Model Mavericks   
      Clara Li '23, Nikki Lin, Rose Porta '23, Quinn White '23, and Kushagra Srivastava (UMass)
    - Best in Group (Panel B): Sexy Data Scientists   
      Sarah Branch, Yaretsy Castro, Camila Maldonado, Su Than Thar Nyi, and Sonia Paredes


- <a href="http://www.science.smith.edu/datafest/2019/04/03/winners-from-five-college-asa-datafest-2019/">2019</a>
    - Best in Show: A-super-NOVA   
    	Audrey Bertin '21, Arielle Dror '20, Clara Rosenberg '20, Kara VanAllen '20
    - Best in Group (Panel B): Data Pirates   
    	Tina Liu '22, Francesca Giardine, Jessica Keast '20
    - Best Multilevel Solution: ggsquad2  
    	Elaona Lemoto '20, Ana Porro, Mathena Abramson '19, Paige Patrick AC, Jordan Moody '20
    - Best External Data: FUN[ction]  
    	Khulood Fahim, Zoya Alam, Melanie Nguyen, Julia Bouzaher
    - Best Actionable Insight: LeGit  
    	Victoria Zheng, Sunni Raleigh, Kelly Pien, Catherine Kung
    - Best Data Insight: Unofficial Intelligence  
    	Yanwan Zhu, Xian (Elaine) Ye, Rachel Yan, Kelly Shen '21, Yifan Ma '20, Nichole Yao
- <a href="http://www.science.smith.edu/datafest/2018/03/27/winners-from-asa-five-college-datafest-2018/">2018</a>
    - Best in Group (Panel B): A-super-NOVA   
    	Audrey Bertin '21, Riley Boeth '18, Emma Livingston '20, Clara Rosenberg '20, Kara VanAllen '20
-	<a href="http://www.science.smith.edu/datafest/2017/04/02/recap-of-winners-from-datafest-2017/">2017</a>
    - Best in Show: DataBest   
    	Zainab Aqdas Rizvi '18, Subashini Sridhar '18J, Ji Young Yun '18, Ji Wong Chung '18 and Van Nguyen '18
    - Best Statistical Interpretation: Normally Distributed   
    	Zixian Li '19, Angie Dinh '17, Abby Doctor '17, Erina Fukuda '18 and Raeesa Alam '19J
    - Best Business Insight: Standard Divination   
    	Isabella Zhu '20, Cas Sweeney '19, Sarah Abowitz '20 and Garcia Sun '20
-	<a href="http://www.science.smith.edu/datafest/2015/03/30/datafest-2015-recap/">2015</a>
    - Best in Show: 2&beta;||!2&beta; <br>
    	Galen Long '15, Sara Stoudt '15, Zhenzhen Tan '15, Aiyi Zhang '15, Weijia (Vega) Zhang '18
-	<a href="http://www.science.smith.edu/datafest/2014/03/31/congratulations-to-all-participants/">2014</a>
    - Best in Show: P-Valuables<br>
  	  Deirdre Fitzpatrick '14, Michele Handy '15, Maja Milosavljevic '14, Sara Stoudt '15, and Dana Udwin '14


### [Undergraduate Statistics Project Competition](https://www.causeweb.org/usproc/USCLAP%20Competition) (USCLAP)

The class project competition is for undergraduate students who conduct projects as part of an introductory or intermediate level statistics course. Most projects submitted to the USCLAP competition involve analyzing real data using existing statistical techniques. Students may choose any topic on which to conduct a study and students may use existing data or collect their own.

Recent winners from Smith include:

- 2022
    - [Honorable Mention (Introductory Statistics)](https://www.causeweb.org/usproc/usclap/2022/spring/winners): Grace Rade '24, Audrey Kim '24, Lisa Li '24, & Joy Mahoney '24  
    *"Analysis Of Age, Race And Income As Factors Of Work Time"*  
    Faculty sponsor: Will Hopper
- 2021
    - [3rd Place (Intermediate Statistics)](https://www.causeweb.org/usproc/usclap/2021/spring/winners): Quinn White '23 and Rose Evard '23  
    *"Predicting Depression in the United States: Are Sexual Orientation, Race, and Income Related to Taking Depression Medication?"*  
    Faculty sponsor: Miles Ott
- 2020
    - [1st Place (Intermediate Statistics)](https://www.causeweb.org/usproc/usclap/2020/fall/winners): Xian Ye '21, Hannah Snell '21, Dianne Caravela '22, & Natalia Iannucci '22  
    *"Bayesian Analysis of Quality of Life and PPE (Personal Protective Equipment) Use During the Coronavirus (COVID-19) Pandemic"*  
    Faculty sponsor: Miles Ott
    - [Honorable Mention (Intermediate Statistics)](https://www.causeweb.org/usproc/usclap/2020/fall/winners): Juliet Ramey-Lariviere '22, Ivy Chen '22, & Kathleen Hablutzel '23  
    *"Measuring Healthcare Access: Are Income and Health Insurance Coverage Associated with whether Americans have a Usual Doctor's Office?"*  
    Faculty sponsor: Miles Ott
    - [1st Place (Intermediate Statistics)](https://www.causeweb.org/usproc/usclap/2020/spring/winners): Clara Li '23, Rose Porta '23  
    *"Analysis of Sleep and Depression as Risk Factors for Diabetes"*  
    Faculty sponsor: Ben Capistrant
- 2018
    - [Honorable Mention (Introductory Statistics)](https://www.causeweb.org/usproc/usclap/2018/spring/winners): Rebecca Wolf '20, Francesca Giardine '20, Denize Keles '20, & Rebecca Miller '20  
    *"Statistical Analysis of Climate Change Variables"*  
    Faculty sponsor: Miles Ott
- 2017
    - [2nd Place (Introductory Statistics)](https://www.causeweb.org/usproc/usclap/2017/fall/winners): Erina Fukuda '18  
    *"Factors that Impact Video Game Sales"*  
    Faculty sponsor: Ulf Aslak Jensen (DIS)
    - [1st Place (Intermediate Statistics)](https://www.causeweb.org/usproc/usclap/2017/fall/winners): Angelica Estrada '18 PB, Jessica Wert '18, Oumayma Koulouh '19  
    *"Helping the Red Cross Predict Flooding in Togo"*  
    Faculty sponsor: Jordan Crouser
    - [2nd Place (First Course in Statistics)](https://www.causeweb.org/usproc/usclap/2017/spring/winners): Ngoc (Angie) Dinh '17, Van Nguyen '18, Abby Doctor '17, Christine Yee '17  
    *"What Are Your Odds?":An Interactive Web Application to Visualize Health Outcomes*  
    Faculty sponsor: Jordan Crouser
    - [3rd Place (Second Course in Statistics)](https://www.causeweb.org/usproc/usclap/2017/spring/winners): Ji Won Chung '18, Zainab Rizvi '18, Subashini Sridhar '18J, Ji Young Yun '18  
    *A Business Opportunity: Targeting Expedia's Niche Market in Travel Packages Via Analytical and Predictive Modeling*  
    Faculty sponsor: Jordan Crouser
- 2016
    - [1st Place (First Course in Statistics)](https://www.causeweb.org/usproc/content/2016-fall-usclap-winners): Madison Laethem '17, Grace Zhan '18  
    *Predicting Student Debt Upon College Graduation*  
    Faculty sponsor: Jordan Crouser
    - [2nd Place (Second Course in Statistics)](https://www.causeweb.org/usproc/content/2016-fall-usclap-winners):Ji Young Yun '18, Wencong Li '18  
    *NYC 311 - What are some of the factors that determine the number of days spent to solve non-emergency issues in New York City?*  
    Faculty sponsor: Jordan Crouser
- 2014
    - [Honorable Mention](https://www.causeweb.org/usproc/2014%20Winning%20Projects): Sara Stoudt '15, Dana Udwin '14, and Kelly Francis '15  
    *WeathR: Twitter perspectives on the weather*  
    Faculty sponsor: Ben Baumer

### [Undergraduate Research Project Competition](https://www.causeweb.org/usproc/USRESP%20Competition) (USRESP)

The research project competition is for undergraduate students who conduct research projects coming from activities like summer research projects, senior capstone course research projects, independent research projects (e.g., independent studies), Honor's college research projects, or extension of class research projects. Some submissions to USRESP are applied research projects using existing statistical/analytical techniques to solve real world problems, which others are involve methodological research involving statistical applications or simulation studies evaluating different techniques. Students may collect their own data or use existing data and students can select any topic to study.

- 2023
    - [1st Place](https://www.causeweb.org/usproc/usresp/2022/fall/winners): Irene Foster '23, Sunshine Schneider '23, Caitlin Timmons '23, Katelyn Diaz '23  
      *Storm Chasers: Synthesizing New England Weather Data on a Dashboard for Emergency Response Workers*  
      Faculty sponsor: Albert Kim

- 2022
    - [Honorable Mention](https://www.causeweb.org/usproc/usresp/2022/spring/winners): Dianne Caravela '22, Amrita Acharya '22J, Emma Kornberg '22, Elisabeth Nesmith '22, & Eunice Kim '22  
      *Does The Compas Needle Always Point Towards Equity? Finding Fairness In The Compas Risk Assessment Algorithm: A Case Study*  
      Faculty sponsor: Ben Baumer

- 2019
    - [3rd Place](https://www.causeweb.org/usproc/usresp/2019/fall/winners): Karen Santamaria '20, Kara Van Allen '20, Maggie X. Wang '20, and Tiffany Xiao '20J  
      *Methods for Freeing Public Election Data from PDFs*  
      Faculty sponsor: Ben Baumer
    
- 2015
    - [2nd Place](https://www.causeweb.org/usproc/usproc/2015-usresp-winners): Sara Stoudt '15  
	    *Geostatistical Models for the Spatial Distribution of Uranium in the Continental United States*  
      Faculty sponsor: Ben Baumer



