---
title: "SDS Newsletter"
author: "Ben Baumer"
date: "July 15, 2026"
---


**Please help us reach out to other alumnae by having them contact Ben (<bbaumer@smith.edu>)!**

## Program Updates


### Previous Updates


- [2025](sds_newsletter_2025.qmd)
- [2024](sds_newsletter_2024.qmd)
- [2023](sds_newsletter_2023.qmd)
- [2022](sds_newsletter_2022.qmd)
- [2021](sds_newsletter_2021.qmd)
- [2020](sds_newsletter_2020.qmd)
- [2019](sds_newsletter_2019.qmd)
- [2018](sds_newsletter_2018.qmd)
- [2017](sds_newsletter_2017.qmd)
- [2016](sds_newsletter_2016.qmd)

## Faculty Updates

#### [Ben Baumer](https://beanumber.github.io/)

#### [Gillian Beltz-Mohrmann](https://gbeltzmo.github.io/)

#### [Shiya Cao](https://scao53.github.io/)

#### [Dusty Christensen](https://www.smith.edu/people/dusty-christensen)

#### [Kaitlyn Cook](https://www.smith.edu/people/kaitlyn-cook)

#### [Randi Garcia](https://www.randilgarcia.com/)

#### [Will Hopper](https://www.smith.edu/people/will-hopper)

#### [Albert Y. Kim](https://www.smith.edu/people/albert-young-sun-kim)

#### [Sara Kirshbaum](https://www.smith.edu/people/sara-kirshbaum)

#### [Katherine M. Kinnaird](https://katherinemkinnaird.net/)

#### [Rebecca Kurtz-Garcia](https://www.smith.edu/people/rebecca-kurtz-garcia)

#### [Ab Mosca '14](https://www.smith.edu/people/ab-mosca)

#### [Lindsay Poirier](https://lindsaypoirier.github.io/)

#### [Nikko Stevens](https://www.smith.edu/people/nikko-stevens)

#### [Kementari Whitcher](https://www.smith.edu/people/kementari-whitcher)

## Alumni Updates

-   Alumni updates will be added HERE

## What's next?

### Joint Statistical Meetings

Many of us will be at the [2026 Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2026/index.cfm) during the first week of August in **BOSTON**!.

Don't miss these events featuring Smithies and current faculty!


Join us for the **Smith JSM get together**:

- [Boqueria Seaport](https://boqueriarestaurant.com/location/bos-seaport/)  
  25 Thomson Pl  
  Boston, MA 02210  
  Monday, August 3rd  
  7 - 8:30 p  

We hope to see you there!
