---
title: "SDS Theses FAQ"
---

## Departmental Honors guidelines

The following procedures were ratified on November 14, 2016 and apply to honors in both Statistical and Data Sciences (SDS) and Mathematical Statistics (MST).

- GPA in major: >= 3.3
- GPA in other courses: >= 3.0
- Exam: Oral presentation[^oral], followed by a private interview with faculty asking questions about the presentation
- Percentages for final honors grade:
    - Evaluation of the Written Thesis (Readers): 60%
    - Grades: 20%
    - Evaluation of the Oral Exam: 20%

[^oral]: The oral presentation typically lasts about 30 minutes. Students and guests are invited to ask questions once the presentation has concluded. Once these questions have been answered, students and guests are asked to leave, so that faculty may ask questions of the presenter in private. 

## Frequently Asked Questions

- Am I eligible for Departmental Honors in SDS or MST? 
    - Please see [the College's policies on departmental honors theses](https://www.smith.edu/academics/class-deans/departmental-honors).
- What characterizes an SDS thesis? 
    - An SDS Honors Thesis needs to **focus on data** in some non-trivial way. Previous SDS theses have accomplished this in various ways. A non-exhaustive list of examples would include:
        - Development focus: build an R package that interfaces with a rich data set and/or provides an interactive dashboard
        - Methodology focus: learn about a sophisticated statistical methodology that is beyond the scope of the regular SDS curriculum and explain it and apply it in context
        - Application focus: investigate a real-world problem using sophisticated statistics and data science techniques and provide a nuanced analysis in context
        - Data focus: collect, curate, and/or document a novel data set using ethnographic techniques
- What characterizes an MST thesis?
    - An MST Honors Thesis is evaluated by members of both the Program in Statistical and Data Sciences and the Department of Mathematical Sciences and should have substantial mathematical *and* statistical content. This might look like:
        - Learning about a sophisticated statistical methodology or area of statistical theory that is beyond the scope of the regular SDS/MST/MTH curriculum, explaining its theoretical basis and underpinnings, and applying it in context
        - Conducting a simulation study to evaluate how statistical methods perform in non-standard data contexts
- Should I do a Departmental Honors Thesis? 
    - It depends. Please talk to your major adviser and your potential first reader.   
      
      Departmental Honors theses are generally most appropriate for students who have completed their major curriculum early, have previous research experience, and are very likely to pursue graduate school in the near future. 
        - For students who want research experience: A departmental honors thesis is *neither the best nor the only* way to gain research experience. Departmental honors theses are independent solo projects (with faculty supervision) that must be completable within two semesters. This represents a narrow swath of what research can be. Joining a research lab is an alternative, and potentially better, way to explore collaborative research and to gain *sustained* (multi-year) research experience. 
        - For students majoring in SDS with a second major: An honors thesis in the *other* major can count towards the application domain requirement for the SDS major. Application-focused theses are generally better situated in a second major (if there is one). 
        - For students interested in graduate school: Many graduate degrees---and PhDs in particular---are *research* degrees and applicants are heavily evaluated on their research ability/promise. Co-authoring a peer-reviewed journal article with a faculty mentor is stronger and more visible sign of research ability than an honors thesis alone. Though some honors thesis projects may be turned into published articles with additional work post-graduation, multi-year work in a research lab is another, more direct path towards publication. Academically speaking, you may find that taking an advanced undergraduate or graduate-level class at UMass is a better investment of your time and can provide better academic preparation than a thesis. For those considering graduate degrees in (bio)statistics, additional coursework in mathematics (particularly in real analysis and measure theory) is strongly recommended.
        - For students who just want Honors: It is true that Departmental Honors theses are the only mechanism Smith has for earning Departmental Honors. However, as noted above, there are often better mechanisms for enriching your academic experience at Smith. 
- What should I do to prepare for a Departmental Honors Thesis?
- When should I start thinking about a Departmental Honors Thesis?
- Who should I ask to be my first and second reader? 
    - Please review the [Faculty Research Profiles](research.qmd) and look for a good match. Please note that faculty have varying schedules and capacities for advising theses, and may or may not be available to serve as one of your readers. 
- Is there a template? 
    - Yes! Please use [`pioneerdown`](https://github.com/SmithCollege-SDS/pioneerdown).

## Archive of previous SDS theses

Please see [our list of previous SDS theses](awards.qmd#departmental-honors) and the Departmental Honors designations that they have received.
Note also that many previous theses are [archived in Smith ScholarWorks](https://scholarworks.smith.edu/sds_etd/). 
