---
title: "Ethics patches in a box"
subtitle: "a clever, topical title"
author: "blinded"
date: "Last updated on `r Sys.Date()`"
bibliography: bibliography.bib
output:
  html_document:
    fig_caption: yes
    theme: lumen
    toc: yes
    toc_depth: 2
    df_print: kable
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

## Description of course/setting

- Actual: *Statistical Analysis of Social Network Data*
- Generic: upper-level course that requires a second course in statistics, and preferably a programming course

## NAS ethical areas

- Privacy and confidentiality,
- Responsible conduct of research,

## Questions/goals addressed

- Give students the experience of collecting social network data, and to experience how there are many subjective choices in the collection of those data.
- Have students consider how abstraction (the way in which data are represented) strips context from the data, and talk about implications of that lack of context
- Students apply general paper on ethics of survey data to the specific context of social network surveys: students create their own understanding of what makes social network data collection ethical. 
- This is meant for the first day of class, so the main goal is to set the tone for the class that ethics must be considered throughout.

## [Bloom taxonomy](https://en.wikipedia.org/wiki/Bloom%27s_taxonomy#/media/File:Bloom%E2%80%99s_Taxonomy_Verbs.png)

- Application: Students apply knowledge of data science ethics in real-world context


## Related work in data science ethics

- @fiesler2020we

## Generalizability

- any collection of data on humans


# Lesson plan for instructors

## Student preparation required

- no technical knowledge required
- after class, read:
    - @hammer2017ethical
    - @kolaczyk2014 (Pages 1-10 and 13-18)

## Activity description

### Warm up: How are people connected to each other?
- Networks are collections of inter-connected entities and in social networks those entities are people
- working in small groups: brainstorm as many possible different social connections that you can think of 
- (after brainstorming is over) Have students share social connections they thought of and write them on the board

### Time to collect data: [*Grey's Anatomy*](https://en.wikipedia.org/wiki/Grey%27s_Anatomy)
- Introduce a TV show or movie in which many people interact with each other in different ways (I chose *Grey's Anatomy* and got a DVD from the College Library)
- Ask each student to pair up.  In pairs: identify two kinds of social connections that you could collect from watching part of *Grey's Anatomy*
- Have students pick which kind of social connection information they will collect
- Show part of the first episode of *Grey's Anatomy* (I showed first 12 minutes) and have students collect the social network information

### Questions to Ask in Data Collection Discussion:
- What did you notice as you were collecting the data?
- Was it always obvious that people were or were not connected?
- How can biases be introduced when collecting social network data? What implications will that have for the conclusions we will make based on the data?
- Assuming that you were a "[fly on the wall](https://idioms.thefreedictionary.com/a+fly+on+the+wall)" instead of watching a TV show, do you have any concerns for collecting these data?

### Homework Portion
- Read @hammer2017ethical and reflect on the following questions:
  * How can you apply the ideas about data ethics from this reading (which is about surveys in general) to social network analysis survey collection? Which ideas carry over to the social network context, which do not?
  * Did collecting the *Grey's Anatomy* data bring up ethical concerns? Why or why not?
  
- Read @kolaczyk2014 (Pages 1-10 and 13-18) 
  * Summarize in your own words the three types of Network Analysis
  * Using *Grey's Anatomy* data as an example: what are potential benefits/harms of conducting these kinds of analyses?
  * Use the social network data you collected from watching *Grey's Anatomy* in class to create an adjaceny list, an edge list, an adjacency matrix. What are the advantages and disadvantages of representing your network data in each of these ways?
  * How does the way we represent data about people change how we consider the ethical implications that can be intwined in the collection and analysis of that data?


## Deliverables

- homework assignment 
- (optional): sets up class discussion for the next class period in which students dicuss their ideas from the reading

# References