---
title: "Mu Sigma Rho"
output:
  html_document:
    toc: false
---

[Mu Sigma Rho](http://www.stat.purdue.edu/~mccabe/msr/) is the national statistics honor society, and the [Boston Chapter of the American Statistical Association](https://community.amstat.org/bostonchapter/home) oversees [nominations](http://www.colby.edu/musigmarho/) from Smith each spring.


```{r, include=FALSE}
library(tidyverse)
```

```{r read-sheet, eval=TRUE, include=FALSE}
library(googlesheets4)
options(gargle_oauth_email = TRUE)
# gs4_auth(email = TRUE)
key <- "1P2ZOOXB5dHwycXZkFYm_3u7M4lEPPm36RJHdMloAZlY"
archive <- read_sheet(key)
```

```{r, include=FALSE, eval=FALSE}
nominees <- read_csv("~/Dropbox/SDS/students/mu_sigma_rho/Spring 2022 Mu sigma Rho.xlsx - mu sigma rho.csv")

x <- nominees %>%
  filter(str_detect(`Class Year`, "22|23J")) %>%
  group_by(Student, `Class Year`, cumGPA) %>%
  count() %>%
  filter(n >= 2) %>%
  arrange(desc(n))
```


```{r, include=FALSE, eval=FALSE}
potential_nominees <- read_sheet("1Uy-pjhe0VSWrRKBaVrhC5bjbT1GSUS2qtuf9Eth3e_c")

nominees <- potential_nominees %>%
  mutate(
    Id = as.numeric(Id),
    not_eligible = SumOfcredit < 8
  ) %>%
#  pivot_longer(matches("CSC|SDS|MTH"), names_to = "course", values_to = "taken")
#    sds291 = sum(c(`MTH 291`, `SDS 291`), na.rm = TRUE)
  filter(
    SumOfcredit >= 8, 
    class %in% c("21", "21J", "22J"),
    CumGPA > 3.2,
    !not_eligible
  ) %>%
  anti_join(archive, by = "Id")

write_csv(nominees, "mu_sigma_rho_2021.csv")
```

```{r, eval=FALSE, include=FALSE}
archive %>%
  mutate(class = as.character(class)) %>%
  filter(class %in% c("21", "21J")) %>%
  select(Id, induction, class, Last, First) %>%
  arrange(induction, class, Last, First) %>%
  print(n = Inf)
```


```{r mu-sigma-rho, fig.cap="Growth of Mu Sigma Rho inductees.", echo=FALSE, warning=FALSE, message=FALSE}
archive %>%
  mutate(
    class = as.character(class),
    class_year = ifelse(class %in% c("NULL", "AC"), 0, induction - (2000 + parse_number(class))),
    class_year = factor(class_year, labels = c("junior", "senior"))
  ) %>%
  group_by(induction, class_year) %>%
  summarize(N = n()) %>%
  ggplot(aes(x = induction, y = N, fill = fct_relevel(class_year, rev))) +
  geom_col() +
  scale_y_continuous("Number of Inductees") + 
  scale_x_continuous("Year of Induction") + 
  sds::scale_fill_smith_d("Class") + 
  labs(title = "Growth of Smith College Mu Sigma Rho inductees")
```

Search the archive to find inductees:

```{r, echo=FALSE, message=FALSE}
archive %>%
  arrange(desc(induction), Last, First) %>%
#  mutate(Name = paste(Last, First, "(", PrefFirst, ")")) %>%
  select(induction, Last, First, PrefFirst, class) %>%
  DT::datatable(options = list(pageLength = 25))
```

