---
title: "SDS Newsletter"
author: "Ben Baumer"
date: "July 15, 2021"
output:
  html_document:
    toc: true
    toc_float: true
---

It's been a wild ride these past 12 months!
Last summer, we still didn't know whether students would be on campus in the fall, or what would happen with the rest of the academic year, the US presidential election, and oh yeah, the coronavirus pandemic.
We now have clarity and closure on...*most?*...of these issues. 
Teaching remotely was exhausting for faculty and students alike, but somehow we muddled through. 
We're united in celebrating the accomplishments of our faculty, students, and alums, and welcoming the promise of a full return to in-person campus life in the fall! 

This newsletter is mostly a distillation of our Twitter @[SmithCollegeSDS](https://twitter.com/SmithCollegeSDS) feed. Please follow us to see more news, updates, and pictures!

There is also a [Facebook group](
https://www.facebook.com/groups/665780273559948/), a Google group, and a [Slack](https://twitter.com/Miles_Ott/status/1242104426921426945). **Please help us reach out to other alumnae by having them contact me!**

## Program Updates

- **Miles Ott '01** was named the 2021 LGBTQ+ Educator of the Year by STEM for Equality! Miles received amazing nomination letters from **Natalie LaBossier '20**, **Emily Daubenspeck '20**, and **Amelia Eigerman '21**, among others. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/Miles_Ott?ref_src=twsrc%5Etfw">@Miles_Ott</a> is the <a href="https://twitter.com/STEMforEquality?ref_src=twsrc%5Etfw">@STEMforEquality</a> 2021 LGBTQ+ Educator of the Year! Congrats! We hope you are celebrating this achievement with <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> and your many student nominators. Learn more about Miles at <a href="https://t.co/QM5J3GRd6e">https://t.co/QM5J3GRd6e</a>. <a href="https://twitter.com/hashtag/STEM?src=hash&amp;ref_src=twsrc%5Etfw">#STEM</a> <a href="https://twitter.com/hashtag/LGBTQIA?src=hash&amp;ref_src=twsrc%5Etfw">#LGBTQIA</a> <a href="https://twitter.com/hashtag/queer?src=hash&amp;ref_src=twsrc%5Etfw">#queer</a> <a href="https://twitter.com/hashtag/Statistics?src=hash&amp;ref_src=twsrc%5Etfw">#Statistics</a> <a href="https://twitter.com/hashtag/Datascience?src=hash&amp;ref_src=twsrc%5Etfw">#Datascience</a> <a href="https://t.co/zynWSvIjXN">pic.twitter.com/zynWSvIjXN</a></p>&mdash; NOGLSTP is Out to Innovate (@STEMforEquality) <a href="https://twitter.com/STEMforEquality/status/1395513119275773953?ref_src=twsrc%5Etfw">May 20, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- **Starry Zhou '21J** and **Hannah Snell '21** shared Smith's portion of the Five College Statistics Prize for their working with Smithies in SDS. 

- **Audrey Bertin '21** won the SDS Research Prize for her honors thesis, titled: "Addressing The Scientific Reproducibility Crisis Through Educational Software Integration". Based on her research, Audrey also co-authored [a peer-reviewed journal paper](https://onlinelibrary.wiley.com/doi/10.1002/sta4.332) that appeared in STAT. 

- **Xian (Elaine) Ye ’21**, **Hannah Snell ’21**, **Dianne Caravela ’22**, **Natalia Iannucci ’22**, **Juliet Ramey-Lariviere ’22**, **Ivy Chen ’22**, **Kathleen Hablutzel ’23**, **Clara Li ’23**, and **Rose Porta ’23** were all recognized by the [Undergraduate Statistics Project Competition](https://www.causeweb.org/usproc/usclap/2020/fall/winners) for their work in intermediate statistics. 

- Teaching remotely led to some opportunities for innovation. Thanks to Jon Caris and the Spatial Analysis Lab, students in SDS 192 were able to tour the MacLeish Field Station virtually during a live drone flight during class!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Gratitude to <a href="https://twitter.com/AirdataUAV?ref_src=twsrc%5Etfw">@AirdataUAV</a> for enabling live stream drone flights for <a href="https://twitter.com/smithcollege?ref_src=twsrc%5Etfw">@smithcollege</a> <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> class. <a href="https://twitter.com/BaumerBen?ref_src=twsrc%5Etfw">@BaumerBen</a> provided great play by play analysis and we plan to do again soon! <a href="https://twitter.com/hashtag/somanymovingparts?src=hash&amp;ref_src=twsrc%5Etfw">#somanymovingparts</a> <a href="https://t.co/tPxR01tvay">pic.twitter.com/tPxR01tvay</a></p>&mdash; GIS @ Smith College (@SmithGIS) <a href="https://twitter.com/SmithGIS/status/1339210090247835648?ref_src=twsrc%5Etfw">December 16, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- **Stephanie Eckman '94** gave a talk in SDS 192 about her research in using computer vision to detect housing units from satellite imagery.  

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thanks for coming to talk to my <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> <a href="https://twitter.com/hashtag/DataScience?src=hash&amp;ref_src=twsrc%5Etfw">#DataScience</a> class today <a href="https://twitter.com/stephnie?ref_src=twsrc%5Etfw">@stephnie</a>!! I really enjoyed hearing about your research and appreciated all the ways in which it connected to topics we&#39;ve raised in the course.</p>&mdash; Ben Baumer (@BaumerBen) <a href="https://twitter.com/BaumerBen/status/1327330660604928002?ref_src=twsrc%5Etfw">November 13, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- Several students will get practical experience with real-world data science projects thanks to the NSF-funded DSC-WAV project. The three-year grant shared with the Five Colleges pairs students with local non-profits. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">A new data sciences program offers Smith students a chance to apply their skills, while also helping community groups solve data problems they might otherwise be unable to tackle. <a href="https://t.co/bznrcubuJY">https://t.co/bznrcubuJY</a> <a href="https://t.co/U70C3gukQk">pic.twitter.com/U70C3gukQk</a></p>&mdash; Smith College (@smithcollege) <a href="https://twitter.com/smithcollege/status/1326170338040958978?ref_src=twsrc%5Etfw">November 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- **Miles Ott '01** and **Mine Dogucu '09** co-authored a textbook on Bayesian statistics.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">📘Excited to share the first 5 chapters of ~Bayes Rules!~ An Introduction to Bayesian Modeling with R, which I have had the absolute joy of working on with <a href="https://twitter.com/MineDogucu?ref_src=twsrc%5Etfw">@MineDogucu</a> and Alicia Johnson of <a href="https://twitter.com/Macalester?ref_src=twsrc%5Etfw">@Macalester</a><br><br>📘Check it out here: <a href="https://t.co/ix6lZLdNaC">https://t.co/ix6lZLdNaC</a> <a href="https://t.co/kvAi9Wf7xf">pic.twitter.com/kvAi9Wf7xf</a></p>&mdash; Miles Ott 🏳️‍⚧️ (he/him) (@Miles_Ott) <a href="https://twitter.com/Miles_Ott/status/1315770302463455232?ref_src=twsrc%5Etfw">October 12, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- **Adriana Beltrán Andrade '22** and **Chichi Wu '22** won the Service Track 🏆 for their &quot;Block&quot; venture in this year&#39;s Draper Competition for Collegiate Women Entrepreneurs!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Congrats to <a href="https://twitter.com/SmithCollegeSDS?ref_src=twsrc%5Etfw">@SmithCollegeSDS</a> majors Adriana Beltrán Andrade &amp; Chichi Wu for winning the Service Track 🏆 for their &quot;Block&quot; venture in this year&#39;s Draper Competition for Collegiate Women Entrepreneurs! <a href="https://t.co/nYjbRt2BNO">https://t.co/nYjbRt2BNO</a> <a href="https://t.co/7eEXMhGvxo">pic.twitter.com/7eEXMhGvxo</a></p>&mdash; Smith College SDS (@SmithCollegeSDS) <a href="https://twitter.com/SmithCollegeSDS/status/1292947110573281288?ref_src=twsrc%5Etfw">August 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- **Marium Tapal '22** published the `fec16` package on CRAN.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hey <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a>! My first R📦&#39;fec16&#39; is live on CRAN. fec16 contains relational data from the 2016 United States Federal Elections in the form of pre-loaded datasets and functions. <br>GitHub repo: <a href="https://t.co/RNcKwAkW0e">https://t.co/RNcKwAkW0e</a></p>&mdash; Marium Tapal (@mariumtapal) <a href="https://twitter.com/mariumtapal/status/1288834414747811840?ref_src=twsrc%5Etfw">July 30, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Previous Updates


- [2020](sds_newsletter_2020.html)
- [2019](sds_newsletter_2019.html)
- [2018](sds_newsletter_2018.html)
- [2017](sds_newsletter_2017.html)
- [2016](sds_newsletter_2016.html)


## Faculty Updates 

I can say with certainty---which is **rare** in our discipline---that the 2020--2021 academic year was the most difficult for the faculty in...who knows how long? 
We all adapted our pedagogy to remote instruction and settled in for the long haul of a year of Zoom meetings and online classes. 
My heart goes out to **Sara Stoudt '15**, who accepted a one-year teaching position and then never got to set foot in her office or in a Smith classroom!

It was nevertheless an eventful year for faculty:

- **Miles Ott '01** was granted tenure and promotion to associate professor in February. To our great sadness, Miles resigned his position at the end of the year to become a [Senior Data Scientist at Johnson & Johnson](https://twitter.com/Miles_Ott/status/1403086377684721667). We wish Miles all the best in his new line of work and will miss him dearly. 
- **Sara Stoudt '15** accepted [a tenure-track position at Bucknell University](https://www.bucknell.edu/fac-staff/sara-stoudt). We're thrilled for Sara and look forward to collaborating with her. 
- We hired **Lindsay Poirier** as a MassMutual assistant professor of statistics and data science. Lindsay is a data anthropologist who comes to us from [UC-Davis](https://lindsaypoirier.faculty.ucdavis.edu/). We're super-excited about the breadth of new course offerings she will offer and the experience she brings to the Program. 
- We hired **Fatou Sanogo** as a Lecturer. [Fatou](https://www.linkedin.com/in/fatoumata-sanogo-447085a8/) just completed her PhD in applied mathematics at the University of Alabama-Birmingham. She'll be teaching mostly introductory statistics and we are lucky to have her here as she starts her career. 
- We'll be searching for **three** tenure-track positions this year!
    - a biostatistician
    - a 2nd MassMutual assistant professor position
    - a joint position to be shared with the Mathematics department for a Mathematical Statistician  
  


#### Ben Baumer

It was a hard year to be Chair! 
We never even had the chance to celebrate my tenure decision before the pandemic threw us all into a tailspin. 
I'm grateful to my family and my colleagues for their perseverance through all the challenges we faced. 

We finished the [2nd edition of *Modern Data Science with R*](https://mdsr-book.github.io/mdsr2e/). 
There are some interesting things starting to come out of the [DSC-WAV project](https://dsc-wav.github.io/www/outreach.html), which now entering its 3rd year. 
In particular, we've been tracking how some of the software development practices (e.g., GitHub and Scrum) we've been implementing with students have fared in the remote working environment. 

I continue to be in awe of the resilience of Smithies (and their general fabulous-ness)!

#### Randi Garcia

This year was full of ups and downs for me...and for many others it seems. In the fall (after pivoting my research questions due to the COVID shut down!) I successfully collected daily-diary data for a research project investigating household and childcare labor among cohabitating couples with at least one person working from home. It was exciting to start analyzing this data set with my students in my Spring 2021 research seminar. We have some interesting results that we'll be writing up for publication together! In addition, this year I had a paper written with **Sarah Bingham '22** on Instagram use and self-objectification accepted for publication in Psychology of Popular Media and I submitted a paper written with **Kat Kyuchukova '19**, **Asha Hinson '19**, and **Lanee Jung '20** on objectification in interactions among women for publication. 

After a Spring 2020 sabbatical and a Fall 2020 course release, I had my first remote teaching experience teaching SDS 290 during J-term this year. Shout out to **Julie Destine '21** and **Audrey Bertin '21** --- I simply could not have taught this crazy [face-paced](https://randilgarcia.github.io/sds290interterm21/schedule.html) J-term course without your assistance and swift grading! And shout out to all of my J-term students for working so hard. It was a pleasure to have that experience with you! In the Spring I taught my Psychology of Women and Gender course and my Research Seminar. It was nice to find that I was still able to build relationships with my students, and to help them build community with each other, even in the remote environment. But I'm definitely ready to get back in the classroom! 

I read lots of classic books this year including *Pride and Prejudice*, the *Harry Potter* series, *Dune*, and the *Golden Compass* series. All for the very first time! I am currently reading the *Lord or the Rings: Two Towers*. I also read [*The Fate of Food*](https://www.amandalittle.com/fateoffood) and [*Braiding Sweetgrass*](https://milkweed.org/book/braiding-sweetgrass) which was amazing --- thanks to **Ester Zhao '21** for the recommendation! There was also a lot of Nintendo playing and gardening in my life.

#### Will Hopper

This fall, I'll be returning to teach my greatest hits, SDS 201 (Statistical Methods for Undergraduates) and SDS 291 (Multiple Regression). I'm most excited to adapt some ideas and methods for creating a more interactive lecture experience, inspired by the experience of teaching online, to the physical classroom. Oddly enough, I've taught more semesters online than in-person, so in some ways returning to campus will be the strange adaptation, rather than the other way around! Regardless of locale, I'm sure I'll continue to be impressed by the tenacity and commitment of the students in my classes.

I continued to enjoy playing competitive Pokémon in the [VGC format](https://www.reddit.com/r/PokemonVGC/comments/5bmuua/so_you_want_to_play_vgc_newcomers_start_here/), and I even won my first prize money (well, $24, but still, it's something!). I'm enjoying the current series 10 ruleset, and looking forward to the upcoming Diamond/Pearl remakes coming this fall. Pokémon is a game **full** of probabilities, so expect a few examples if you're taking one of my classes!

#### Albert Y. Kim

Hello SDS world! It being my sabbatical year, I taught a single course in the fall: SDS 390 Ecological Forecasting. It was among the most rewarding teaching experiences of my career. Despite the remote circumstances, I felt like I had a chance to really bond with every student in the class. Not only did we apply data science tools and technology to answer ecological questions, but we also discussed larger topics like time-management, healthy work-life balance, and interpersonal skills in workplace settings.

On the research side of things, my work in forest ecology has been getting curiouser and curiouser. Here are three projects I’ve been involved in:

1. Studying the growth phenology of trees i.e. how year-to-year changes in within-year climate variation is impacting the growth of trees. We found evidence that suggests even though growing seasons are getting longer (springs that start earlier and falls that end later), this is not translating to increased tree growth :(
2. Using Bayesian Hidden Markov Models to fuse disparate sources of tree data into a single model with the ultimate goal of forecasting the growth of trees. 
3. Implementing GitHub Actions continuous integration cyberinfrastructure to automate quality assurance and control of data on forest dynamics. The basic pipeline is: ecologists gather data in the field and then push the resulting spreadsheets to GitHub. This will then trigger data scripts that will automatically verify data quality and produce a dashboard of reports.

Other than than during this year of COVID I’ve been playing a lot of tennis, fell into a Nintendo Switch Zelda Breath of the Wild wormhole for most of late December and January, and been doing a lot of soul-searching as a result of the anti-Asian hate crimes that occurred in Atlanta in March. Lastly, my beloved Montreal Canadiens made it to the NHL Stanley Cup Finals for the first time since I was 12 years old. Despite an odds-defying run to the finals, they lost in 5 games to the repeat champion Tampa Bay Lightning. 



#### Katherine M. Kinnaird

With both teaching and conferences all virtual, this year was like no other for sure! In the spring, I taught two different machine learning classes: _Modeling for Machine Learning_ (SDS 293) and _Computational Machine Learning_ (CSC 294). 
It was great to [gather](https://gather.town/) and work through the details of various Machine Learning concepts. 

Since last newsletter, I once again was a co-organizer for the [Women In Music Information Retrieval Workshop](https://wimir.wordpress.com/2020/08/13/wimir-workshop-2020-project-guides/) and for the [Machine Learning for Media Discovery Workshop](https://sites.google.com/view/ml4md2020/home). 
I had a lot of fun working with collaborators this year. 
[Automatic Hierarchy Expansion for Improved Structure and Chord Evaluation](https://transactions.ismir.net/articles/10.5334/tismir.71/) with [Brian McFee](https://brianmcfee.net/) expands on our ISMIR 2019 paper. 
It was also fun to integrate my interests in MIR and pedagogy in [Interactive Learning of Signal Processing Through Music: Making Fourier Analysis Concrete for Students](https://ieeexplore.ieee.org/document/9418542) with [Meinard Mueller](https://www.audiolabs-erlangen.de/fau/professor/mueller) and Brian McFee. 
This summer, I've been privileged to work with five students through the SURF program, which is a great way to wrap up this year of virtual collaboration 

#### [Scott LaCombe](www.scottlacombe.com)

After my first year virtual teaching, I'm so excited to finally be teaching in person and getting to participate in some Smithie traditions this Fall (I've been promised donuts). This Fall, I will be teaching my first dual prefixed course, SDS/GOV 338 Political Networks, and I look forward building more connections between GOV ad SDS.

I used the pandemic as an excuse to explore every trail and state park I can with my dog, Gollum. Say hi if you see us walking around campus and I'm always looking for new trail recommendations! In the past year I have finished an [upcoming book](https://global.oup.com/academic/product/choosing-the-future-9780197585757?cc=us&lang=en&) with Karen Mossberger and Caroline Tolbert on the importance of broadband for state and local economic and political development, and was honored to receive the best dissertation award from the State Politics and Policy Section of the American Political Science Association. I also have published papers in State Politics and Policy Quarterly, Politics Research Quarterly, and my first solo-authored publication in Social Science Quarterly.


#### Lindsay Poirier

I am so thrilled to be joining the faculty in SDS at Smith! Last month, I road-tripped across the country from Sacramento, CA where I was an Assistant Professor at UC Davis in a program called Science and Technology Studies (STS). STS is a social science discipline that studies the intricate ways science, technology, culture, and politics all co-constitute each other. Many of the courses that I will be teaching at Smith (such as *Data Ethnography* and *Data and Social Justice*) approach data science from this angle.

As if I wasn't excited enough for my start day at Smith, that same day an article I've been working on for a year and half was [published](https://journals.sagepub.com/doi/full/10.1177/20539517211029322) in the journal *Big Data and Society*. It describes how I've taught students to perform critical readings of datasets like the NYPD's Stop, Question, and Frisk dataset and the EPA's Toxic Release Inventory. This year I also [published](https://www.tandfonline.com/doi/abs/10.1080/09502386.2021.1895256) in the *Journal of Cultural Studies*, [co-published](https://sciencetechnologystudies.journal.fi/article/view/89782) in the *Science and Technology Studies* journal, and [collaborated](https://critical-data-analysis.org/) with some amazing students and colleagues on the development of public interest [databases](https://critical-data-analysis.org/general-plan-map/) and [mapping tools](https://critical-data-analysis.org/shiny/proximity/proximity-app/). I can't wait to bring Smith students on to some of these projects. I spent most evenings in 2021 cooking, working on mosaic projects, and attempting to match the energy of my spunky pup Maddie. Like me, she's loving life here in Northampton!

#### Fatou Sanogo

I am excited to be joining the SDS program as a lecturer for the year! I just finished my PhD in applied mathematics at the University of Alabama at Birmingham (UAB) this summer and I am looking forward to teaching intro stats and Modeling for Machine Learning at Smith.

I have lived in Birmingham since I first came to the US back in 2013 and this will be a big move for me. I can’t wait to start this new adventure at Smith :) I am planning on a 3 days road trip from Birmingham to Northampton which should be fun!

## Alumni Updates

- [Anna Ballou '20](https://www.linkedin.com/in/anna-ballou/): I just finished my first year of my PhD in Quantitative Epidemiology at the University of North Carolina, Chapel Hill.  I am studying the sex-specific effects of the genetic architecture of various diseases. I've also worked on generating several graphics and figures for my lab's publications. 

- [Brittany Bennett '16](https://www.linkedin.com/in/thebbennett/): is on her second year of serving as the Data Director of the Sunrise Movement. She leverages analytics engineering to uncover insight for organizers working to pass a Green New Deal. [You can follow her writing here](https://www.brittanybennett.com/blog)

- [Stephanie Eckman '94](https://www.linkedin.com/in/stephanie-eckman-090224aa/): Currently a Fellow at RTI International where I conduct research into data quality. I was elected a fellow of the ASA this year.

- [Shuli Hu '18](https://www.linkedin.com/in/shuli-hu-371309a6): I finished the [Research Assistant Program](https://www.imf.org/en/About/Recruitment/working-at-the-imf/research-assistant-program) at the International Monetary Fund and will be starting the MBA program at the University of Cambridge in a few months. I cannot ask for a more fulfilling and delightful post-undergrad experience. Besides, DC is a beautiful city for young adults. Working from home has made us even busier. After a hectic year, I am finally taking a break and spending more time with family and friends.

- [Jennifer Kirk '08](linkedin.com/in/jennifer-l-kirk-4412875/): I’m still happily working as a statistical reviewer at US FDA’s Center for Biologics Evaluation and Research. I work primarily on vaccines, and the past year or so has been quite interesting, if nothing else. I’m also a member of the steering committee for the ASA Biopharm Section 2021 Regulator-Industry Workshop.  
  I’d like to put in an advertisement for the FDA’s summer fellowship program which is open to undergrads, grad students, and recent graduates in STEM fields (including non-citizens): https://orise.orau.gov/fda/.  
  I think the FDA is also currently hiring for PhD statisticians positions (maybe also masters, depends on the group) for citizens and non-citizens, if any alums are searching for jobs. Job advertisements are usually posted to the ASA’s job listing--let me know if you need a link and I can get one from work.

- [Maja Miloslavjevic '14](https://www.linkedin.com/in/maja-milosavljevic-52762297/): I'm about to have my 5 year anniversary at Microsoft in a few months. I spent the first few years as a Program Manager but switched career tracks and am now a Data & Applied Scientist. It feels so good to be back to my DS roots! 

- [Lizzy (Atkins) Offermann '15](https://www.linkedin.com/in/elizabethoffermann/): Back in December 2020, I started my current role as the Senior Business Analyst for the 1,500+ provider Clinically Integrated Network for LifeBridge Health, a $2.5 billion regional health care organization based in northwest Baltimore and the surrounding counties. I govern the data quality and data flow across multiple electronic medical record (EMR) systems among a range of commercial, Medicaid, and Medicare value-based care programs, contributing to a deep knowledge of data integration in and out of EMRs. I have enjoyed working on an executive-level, overseeing the data for a multi-hospital network and providing usable data visualizations to leadership. In the meantime, I have been finishing up my master’s degree in Clinical and Translational Research from George Washington University and will officially conclude by the end of next month! I am currently working on my master's capstone project with Randy Frost, Professor Emeritus of Psychology and it has been truly fabulous to reconnect especially over an interesting study! In my free time (what is that again?), I have been busy enjoying life with my 3.5 year old twins and husband, continuing my role as the head of the Smith Alumnae Admissions for the tri-state area, appreciating my role on the Board of the Smith College Club of Baltimore, and have been progressing in my role as Treasurer on the Smith Class of 2015 Cabinet.

- [Sara Stoudt '15](https://sastoudt.github.io/): I spent the year teaching other Smithies! My favorite activity was making ["data phys"](https://nebigdatahub.org/data-visualization-beyond-the-screen/) to help visualizations come to life off our screens. Another highlight of the year was the release of Deb Nolan and my book, *Communicating with Data: The Art of Writing for Data Science*. [Check it out!](https://twitter.com/sastoudt/status/1390675020209340420?s=20). Now I'm off to my next adventure at Bucknell University where I'll start as an Assistant Professor in the fall. 

- [Kara Van Allen '20](https://www.linkedin.com/in/karavanallen/): I moved to Somerville just over a year ago and started working as a Litigation Analyst for a market research firm in Waltham. While I have enjoyed it as my first job after Smith, I am ready for my next adventure, hopefully one with a stronger statistics focus. I would love any and all support or leads from my Smith network!


## What's next? 

### Joint Statistical Meetings

Many of us will be at the virtual [2021 Joint Statistical Meetings](https://ww2.amstat.org/meetings/jsm/2021/onlineprogram/index.cfm) during the second week of August. 
We wish we could see you in person, but we'll have to settle for Zoom waves this year. `r emo::ji("disappointed")`

### StatFest

[StatFest 2021](https://community.amstat.org/cmis/events/statfest/statfest-2021) will also be virtual in September.

### Women in Statistics and Data Science Conference

[WSDS 2021](https://ww2.amstat.org/meetings/wsds/2021/) will also be virtual in October. 
