---
title: "SDS Newsletter"
author: "Ben Baumer"
date: "July 15, 2023"
---

This newsletter is mostly a distillation of our Twitter @[SmithCollegeSDS](https://twitter.com/SmithCollegeSDS) feed. Please follow us to see more news, updates, and pictures!

There is also a [Facebook group](
https://www.facebook.com/groups/665780273559948/), a Google group, and a [Slack](https://twitter.com/Miles_Ott/status/1242104426921426945). **Please help us reach out to other alumnae by having them contact me!**

## Program Updates

- Smith teams garnered [two out of three Best In awards](https://www.science.smith.edu/datafest/2023/04/10/recap-from-the-2023-asa-five-college-datafest/) at this year’s Five College DataFest held at the University of Massachusetts Amherst. The Smith teams were The Model Mavericks, who won Best in Show (**Clara Li ’23**, **Nikki Lin ’25**, **Rose Porta ’23**, **Quinn White ’23**), and the Sexy Data Scientists, who won Best in Group (**Sarah Branch ’24**, **Yaretsy Castro ’25J**, **Camila Maldonado ’24**, **Su Than Thar Nyi ’24J** and **Sonia Paredes ’23**). 

- An article co-authored by five members of the department was awarded the [Jackie Dietz Award](https://www.amstat.org/your-career/awards/jackie-dietz-best-journal-of-statistics-and-data-science-education-paper-award) for the 2022 Best Paper published in the *Journal of Statistics and Data Science Education*. The paper is titled "Integrating Data Science Ethics Into an Undergraduate Major: A Case Study", and was written by **Benjamin S. Baumer**, **Randi L. Garcia**, **Albert Y. Kim**, **Katherine M. Kinnaird** & **Miles Q. Ott '01**. 
- Our work on the [DSC-WAV](https://dsc-wav.github.io/www) project was written up in the [Grécourt Gate](https://www.smith.edu/news/new-pathways-for-students-in-data-sciences). This article features **AJ Haller '22J**
- Students from SDS 236 (data journalism) wrote two articles that appeared on the front page (above the fold!) of the Daily Hampshire Gazette:
    - [A higher ed game-changer?: Could MassReconnect change college education in Massachusetts? Experts say yes](https://www.gazettenet.com/Could-the-MassReconnect-Program-Change-College-Education-in-Massachusetts-51056620), by **Naylynn Tañón Reyes '23**, **Swaha Bhattacharya '23**, and **Tint Tha Ra Wun '23J**
    - [Combating the crises: Northampton organizations eye ways to  address  mental health challenges among LGBTQ+ youth](https://www.gazettenet.com/Northampton-organizations-combat-LGBTQ--mental-health-crisis-51225706), by **Vivian Almaraz '23**, **Victoria Georgiu '23**, **Clara Li '23**

### Previous Updates

- [2022](sds_newsletter_2022.html)
- [2021](sds_newsletter_2021.html)
- [2020](sds_newsletter_2020.html)
- [2019](sds_newsletter_2019.html)
- [2018](sds_newsletter_2018.html)
- [2017](sds_newsletter_2017.html)
- [2016](sds_newsletter_2016.html)


## Faculty Updates 

- [**Albert Kim** was promoted](https://www.smith.edu/news/faculty-2023-tenure-and-promotions) to associate professor with tenure! **Ben Baumer** was also promoted to full Professor. 
- **Albert Kim** is the 2023 winner of the [Waller Education Award](https://www.amstat.org/your-career/awards/waller-awards), given annually by the ASA Section on Statistics and Data Science Education! Previous winners from Smith include Ben Baumer (2019) and Nick Horton (2009). 
- We hired [**Casey Berger**](https://www.caseyeberger.com/) to a joint tenure-track position with the Physics department. Casey has been teaching at Smith already and her research is in applying high performance computing and machine learning methods to many-body quantum systems. She has already designed a new course, SDS 271, which she will offer in the fall as a Python-based alternative to SDS 270. Casey was just recently elected as a Member-At-Large for the Topical Group in Data Science within the American Physics Society. We're super-excited to keep her at Smith!
- We also hired **Rebecca Kurtz-Garcia** into a joint tenure-track position with the Mathematical Sciences department. Rebecca comes to us from the University of California, Riverside, where she recently completed her Ph.D. in statistics. Rebecca works in the intersection of time series analysis, econometrics, spectral analysis, and steady state simulation. She is starting as a Project NExT fellow this summer, and will be teaching introductory statistics and mathematical statistics in her first year. Yay!
- After completing his first year, **Jared Joseph** is moving on to pursue a permanent job in the criminal investigations unit of the Internal Revenue Service. We're sad to see Jared go, but excited to see what he does next!


#### [Ben Baumer](https://beanumber.github.io/www)

I am about to embark on what I can only hope will be a fantastic adventure during the full-year sabbatical I'm now starting: my family and I will spend the year in Medellín, Colombia! 
I will have an appointment as a Visiting Faculty member at the [Universidad EAFIT](https://www.eafit.edu.co/), and I am also anticipating extending my current role as interim Editor-in-Chief of the [*Journal of Quantitative Analysis in Sports*](https://www.degruyter.com/journal/key/jqas/html?lang=en) for a three-year term. 
Learning a new language in your forties hasn't been easy, but I took SPN 200 at Smith this spring with Prof. Adrián Gras-Velazquez and learned a lot while making some new friends. 

Cuando vuelvo hablaremos español juntos!

#### Casey Berger

#### Shiya Cao

Year one at Smith was good, and I enjoyed research, teaching, and importantly, a supportive environment in SDS and Smith. In Fall 2022, I created the [Disability Inclusion Analytics Lab (DIAL)](https://scao53.github.io/) to advance my research in disability inclusion and broader social inclusion topics. I had the pleasure to work with six Smithies **Linh Pham ’25**, **Zhirou Liu ’25**, **Christy Yang ’25**, **Vicky Xu ’26**, **Nikki Lin ’25**, and **Amber Liu ’24** in my lab this year. A paper on Examining Environmental Barriers for Disabled Employees in Different Industries and Work Spaces I wrote with **Christy Yang ’25** and **Vicky Xu ’26** was accepted by *WSDS 2023*. This summer four SURF students (**Christy Yang ’25**, **Vicky Xu ’26**, **Nikki Lin ’25**, and **Amber Liu ’24**) joined my lab and worked on two research projects: (1) Integrating Disability Inclusion Components into Introductory Data Science Pedagogy and (2) Examining the Intersection of Disability, Race, and Gender in Shaping the Employment Outcomes of Higher Educated Individuals. I also advised **Vicky Xu ’26** on a poster presentation she gave at the *2022 NextGen Data Science Day Conference*. In addition, my coauthored book chapter titled "The Chains that Bind: Gender, Disability, Race, and IT Accommodations" was [published](https://www.elgaronline.com/edcollchap/book/9781800377929/book-part-9781800377929-21.xml). I also gave a research talk at the *UMASS Amherst Statistics and Data Science Seminar Series* in Spring 2023. Moreover, I went to my first SDSS, attended some interesting talks, and met people who share similar research interests. This upcoming year I will continue working on publishing my dissertation papers, writing up papers from the lab projects, and explore some new research streams related to disability inclusion, statistics, and accessibility. 

This fall, I will continue to teach SDS 192 Introduction to Data Science (taught two semesters this past year. Love it!) and develop and teach a research seminar course: SDS 300 Disability Inclusion and Data Analytics (so excited!). In the spring, I will also teach SDS 410 Capstone (looking forward!). 

I am also very proud of our book club this year! We read six books: Stoner, The Memory Police, Seven Empty Houses, The Seven Moons of Maali Almeida, Tomorrow, and Tomorrow, and Tomorrow, Lessons in Chemistry. We are currently reading The Personal Librarian. Looking forward to reading more books with my peers!

#### Kaitlyn Cook

Filler!

#### Randi Garcia

On September 21, 2023 my daughter Devyn Sequoia Durbin was born! She is amazing and kept me very busy this year. I was lucky to have enjoyed parental leave in the fall and then a sabbatical in the spring. I took minimal time for research this year, but I did continue my collaborations with Nicole Campione-Barr at the University of Missouri on adolescent disclosure and family systems and with Sarah Witkowski in the Exercise and Sport Studies department here at Smith on perimenopause symptoms, activity, and cardiovascular health. I also took on a Associate Editor role at the Journal of Personality and Social Psychology. 

As much as I enjoyed my time with family, I am excited to get back to teaching and research in the fall!! I also look forward to taking over as Chair of SDS next year so Ben can take a much needed break. Thank you for your service Ben!

#### Will Hopper

#### [Jared Joseph](https://jnjoseph.com/)


#### Albert Y. Kim

2022-2023 was a big academic year for me, both on personal and professional fronts. 
First, my spouse and I survived our first year of raising our beautiful daughter Gigi. Nothing describes 
the experience better that the old adage about parenting: "The days are long, but the years are short." Second, I got tenure and hence promoted to Associate Professor. 
It's been a long time since I first started teaching at Reed College in 2013, but the 
journey has been a rewarding one. In particular, I got two papers published that I'm very proud of:

1. In Methods in Ecology and Evolution: Kim et al. (2022) ["Implementing GitHub Actions continuous integration to reduce error rates in ecological data collection"](https://doi.org/10.1111/2041-210X.13982)
1. In Nature: Dow et al. (2022) ["Warm springs alter timing but not total growth of temperate deciduous trees"](https://doi.org/10.1038/s41586-022-05092-3)

This coming year, I will be teaching SDS 390 Ecological Forecasting and SDS 410 Capstone in the fall and SDS 220 Intro Stats in the spring. 



#### [Katherine M. Kinnaird](https://katherinemkinnaird.net/)

#### Rebecca Kurtz-Garcia


#### [Scott LaCombe](www.scottlacombe.com)

Year three at Smith was my favorite so far, and I've really enjoyed seeing all the traditions come back in full force! The past year has been full of collaborations with students, and I had my first opportunity to take Smithies with me to the Midwest Political Science Association Conference.

This past Spring, I was able to start up the State Politics Lab through the Humanities and Social Science Lab program on campus. This lab focuses on tracking state legislatures across the American states to see what policy networks are forming. In particular, we are currently tracking laws around LGBT topics and are looking to collaborate with journalists and activists to get a better understanding of why some states pass restrictions and others do not. We are in the middle of data collection right now, but plan on starting to analyze the data this Fall and present our work. This research lies at the intersection of Government and Data Science, so please reach out if you are interested in joining our team this Fall. My reserach is continuing to focus on how public opinion is translated into policy across the states, and using network analysis to study how states are influenicng each other. 

This upcoming year, I will be teaching *Introduction to Probability and Statistics* (SDS 220) in the Fall, as well as *The Politics of Public Policy* (GOV 207) for the Government department.  I will be on sabbatical in the Spring, but will be around campus. 


#### [Lindsay Poirier](https://lindsaypoirier.github.io/)



## Alumni Updates

- **[Brittany Bennett '16](https://www.brittanybennett.com/)**: I am leading the analytics and engineering at Working Families Party as their Data Director, working to find ways to leverage data to win more elections. This role has challenged me in so many ways. I am dipping my toes into more advanced data engineering practices, DevOps, analytics engineering, the wild west of vendor politics, contract negotiations, and product development. While the time I spend coding is becoming less and less, I'm deeply enjoying my work at the intersection of data and electoral politics. Otherwise, I'm enjoying plenty of time in the kitchen as a hobbyist home-chef and have added many new recipes to my cooking Instagram. Pittsburgh is still home for now, though I have my eyes on Chicago or Philly. 
- [**Christa Chiao '15**](https://www.linkedin.com/in/christa-c-3a674453/): I am continuing to work in campaign-side electoral politics in data science and data engineering roles. This past year I graduated from the QMSS program at Columbia University and later worked as a Senior Data Scientist at the Democratic Senatorial Campaign Committee during the 2022 midterm cycle. I'm looking forward to electing more Democrats in 2024 and to keep learning about survey research, managing data teams, and more. 
- [**Sara Stoudt '15**](https://sastoudt.github.io/): Year 2 teaching at Bucknell was a busy one! Here are some things I’m proud of from the year: we released our second [Data Science by Design Anthology ("Our Environment")](https://datasciencebydesign.org/book-2), I developed and taught a new first year seminar ["Storytelling with Data"](https://docs.google.com/document/d/19HnV9PRFGb4djHFBuL_dhYraV4fL9zRoGwPhQoE9BAs/edit?usp=sharing), I got to give an [USCOTS keynote](https://www.causeweb.org/cause/uscots/uscots23/keynotes/4) and be on an [SDSS panel](https://ww2.amstat.org/meetings/sdss/2023/featuredspeakers.cfm) with superstars [**Christine Zhang '09**](https://twitter.com/christinezhang?lang=en) (another Smithie, we're everywhere) and [Roger Peng](https://rdpeng.org/) (I only fangirled a little over his podcasts). I'm on pre-tenure leave this upcoming school year, so if anyone is in need of a seminar speaker, I'm up for a travel adventure. :D 
- **Liz Stuart 97** (math major): I've been [named Chair of the Biostatistics Department at Johns Hopkins Bloomberg School of Public Health](https://publichealth.jhu.edu/2023/elizabeth-stuart-named-biostatistics-department-chair).  She would love to welcome more Smith alums to the field and Department!  She also is succeeding former Smith faculty member Nick Horton as co-chair of the National Academies’ Committee on Applied and Theoretical Statistics.
- **Dana Udwin '14**: I'm happy to report that I defended my dissertation in biostatistics and joined the JHU Applied Physics Laboratory as a senior data scientist.
- **Maggie Wang '20**: I start my PhD in political methodology at UChi this fall. Shout out to Ben and Scott for their help during the application process!


## What's next? 

### Joint Statistical Meetings

Many of us will be at the [2023 Joint Statistical Meetings](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.pubSearchOptions&style=0) during the second week of August. 
Don't miss these events featuring Smithies!

- [IOL: Applications of Computational Social Science to Diverse Fields](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1869)  
  Stephanie Eckman '94
- [The Future of Statistics in Education Research: Recommendations from 3 National Academies Reports](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1723)  
  Stephanie Eckman '94
- [Rosenbaum & Rubin’s Propensity Score: Impact, Introspection and Discussion 40 years later](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1646)  
  Elizabeth Stuart '97
- [Introducing Bayesian methods in statistics and data science curriculum](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=2582)  
  Mine Dogucu '09
- [Big Data with Rare Events, and Applications in Safety](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1791)  
  Maria Terres '09
- [Collaborative writing workflows: building blocks towards reproducibility](https://ww2.aievolution.com/JSMAnnual/index.cfm?do=ev.viewEv&ev=1560)  
  Sara Stoudt '15

We hope to see you **in person**!


### StatFest

[StatFest 2023](https://community.amstat.org/cmis/events/statfest/statfest-2023) will also be virtual in September.

### Women in Statistics and Data Science Conference

[WSDS 2023](https://ww2.amstat.org/meetings/wsds/2023/) will be in Seattle in October. 
